### ISSUE TITLE
Automated deployments when we create a tag

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#122]
Hello @eliskovets 

I am not sure if this repository is the best place for this task but I would at least like to start a discussion. :)

What do you think about the idea to do some automation in regards of deploying a test build on simulated production environment?

We can do it under test domain similar to https://demo.basicrum.com/  where we may have https://latest.basicrum.com/ 

We can shoot beacons constantly to this domain and test scenarios when we have DB migrations, planned downtimes and so on.

We also may have a branch called **demo** and we may deploy to https://demo.basicrum.com/ once we merge stuff to **demo**.

This is just an idea but I would love to hear your opinion :)

**Comment by eliskovets** [comment]
Hi @ceckoslab 
That's a great idea. I believe it would be better to use [demo.basicrum.com](demo.basicrum.com) to present actual state of basic rum project, but only in case if you have no other plans for this domain. 

Regarding specific branch which can be used to trigger deployment. For now it can be an option as the project haven't reached a desired state yet, but I would suggest to switch to track changes in `master` instead of specific `demo` branch. 

When we are ready with a prototype which can be shown to the world, then it would be better to switch to release(tags) based deployments and reconfigure deployment from master to another environment, probably [master.basicrum.demo](master.basicrum.demo) which can be used for internal needs.

**Comment by ceckoslab** [comment]
Hello @eliskovets 

Let's use master as a trigger for a demo deployment. 

We will need to create a develop branch because I would like to merge from time to time to a branch that may unstable code.
