### ISSUE TITLE
Problems in code

### ISSUE THREAD

**Issue by korzol** [basicrum/backoffice#147]
Hello @ceckoslab 
Here are few files which in my opinion have some problems with code style and could be improved
src/BasicRum/DiagramBuilder.php
This file is too complicated and can be break into several classes

src/BasicRum/WaterfallSvgRenderer.php contains SVG waterfall generation. 
Probably it is easier to use some js library for waterfall generation, like plotly, which we already using.
[Plotly Waterfall Documentation](https://plotly.com/javascript/waterfall-charts/)
[Codepen Example](https://codepen.io/pen/?&editable=true=https%3A%2F%2Fplotly.com%2Fjavascript%2Fwaterfall-charts%2F)

I am going to update this issue once I found new problem

**Comment by ceckoslab** [comment]
Hello @korzol 

Could you share more details and suggestion what you think could be changed and what you think is best practice?

In relation with the suggestion about using a JS library for the waterfall. In early discussion I mentioned that for `src/BasicRum/WaterfallSvgRenderer.php` I ported a part of a JS library. This is the library: https://github.com/micmro/PerfCascade

We can use this Library but we would need to do our own modifications because the library is built to render HAR files which is not exactly what we need. I would like to have our own version of the library but not now because it requires from us to learn TypeScript but let's not dive in to this right now.

**Comment by korzol** [comment]
Hello @ceckoslab 
As of src/BasicRum/DiagramBuilder.php it contains only one method - build, but this method is too long. Contains three if()'s, like ```
if ('distribution' === $renderType) {
...
}
if ('time_series' === $renderType) {
...
}
if ('plane' === $renderType) {
...
}

```
and  too many levels of indentation. 
For example it can be split into several classes utilizes factory pattern.

**Comment by ceckoslab** [comment]
Hello @korzol 

Could you purpose a new file structure and an perhaps do some refactoring?

**Comment by korzol** [comment]
Hello @ceckoslab 
DiagramBuilder remains in place and adding another several files
src/BasicRum/DiagramBuilder.php
```
src/Diagram/Builder/
                                Plane.php
                                Distribution.php
                                TimeSeries.php
                                RenderTypeFactory.php
```

So DiagramBuilder calls RenderTypeFactory and all the work is happening there. Not in DiagramBuilder anymore
