### ISSUE TITLE
Failed to generate Waterfalls using docker provided in project

### ISSUE THREAD

**Issue by bubble501** [basicrum/backoffice#36]
Hello

I install backoffice successfully using docker following the instruction in the project. however, I got the following error when I try to generate waterfalls:

http://172.16.97.99:8086/diagrams/beacon/draw

An exception occurred while executing 'SELECT t0.page_view_id AS page_view_id_1, t0.beacon AS beacon_2 FROM beacons t0 WHERE t0.page_view_id = ? LIMIT 1' with params [87430]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'basicrum_demo.beacons' doesn't exist

Then i dig a little bit deeper, it seems that the data(docker\db\data\basicrum_demo_2019-04-28.sql.gz) is outdated compare to the latest code. (at leat there is no table Beacons which exist in the code).

here is my question:
1.  would you mind updating the basicrum_demo so that it keep in line with code?
2. Where can i find the document about how to generate the empty table using the code ?

**Comment by ceckoslab** [comment]
Hello @bubble501 ,

Thanks for opening this issue. 

Right now I am in the middle of massive refactoring but I should complete it till Monday - August 5th, 2019.

Is it possible that you wait till then? I will reach you again with updated database schema and code.

Also do you mind if we exchange emails because I am wondering how you would use Basic RUM. I also can provide you with some idea how you can start collecting beacons just now and later import them in a stable version of Basic RUM.

Nice day!

**Comment by bubble501** [comment]
sure, thanks for the quick response.

**Comment by ceckoslab** [comment]
Hello @bubble501 

I am still testing some things around the docker setup. It will take one more day until I push the changes to this repo. Should be ready for tomorrow.

**Comment by ceckoslab** [comment]
Hello @bubble501 

I worked on the issue and I generated a new database that reflects the latest code base. if you are curious you may look the updated live demo: https://demo.basicrum.com/

But back to the issue :)

I decided to remove the DATA initialization part out of the project because it requires gigantic archive files to exist in this git repository and I don't find this being the right solution.

Could you follow the following steps and let me know if it works for you?

Run all commands from the root folder of the project.

1. ```docker-compose -f docker/docker-compose.yml down```
2.  ```docker-compose -f docker/docker-compose.yml rm```
3. ```git pull```
4. ```docker-compose -f docker/docker-compose.yml build --no-cache```
6. ```docker-compose -f docker/docker-compose.yml up -d```
7. ```docker exec basicrum_bo_php composer update symfony/flex --no-plugins --no-scripts```
8. ```curl https://www.revampix.com/basic_rum/test_data/may-july-2019.sql.gz -o may-july-2019.sql.gz```
9. ```gunzip -k may-july-2019.sql.gz```
10. ```cat may-july-2019.sql | docker exec -i basicrum_bo_mysql sh -c 'mysql -uroot -prootsecret'```
11.  ```docker exec -it basicrum_bo_php php bin/console c:c```
12. ```docker exec -it basicrum_bo_php php bin/console basicrum:cache:clean```
13. ```rm may-july-2019.sql.gz```

Many steps! I hope you none will fail. I promise to think about how to make the onboarding process more pleasant.

Please let me know if this works for you.

**Comment by ceckoslab** [comment]
I am closing this issue because I performed 2 tests that I believe are enough in order to prove that it works.

The tests:
 1. Loading the waterfall section existing schema but no records. **No errors!** 
 2. Loading the waterfall section with data in the DB. **No errors! + We see see a waterfalls for different page views.**
